obj-m	+= abrolhos.o
ccflags-y	+= -DCONFIG_EDGETPU_TELEMETRY_TRACE=1 -I$(src)/include

edgetpu-fw-objs := edgetpu-firmware.o edgetpu-firmware-util.o edgetpu-shared-fw.o
edgetpu-objs	:= edgetpu-mailbox.o edgetpu-kci.o edgetpu-telemetry.o edgetpu-mapping.o edgetpu-map-dmabuf.o edgetpu-async.o $(edgetpu-fw-objs)
abrolhos-y	:= abrolhos-device.o abrolhos-device-group.o abrolhos-direct.o abrolhos-core.o abrolhos-platform.o abrolhos-iommu.o abrolhos-firmware.o edgetpu-thermal.o $(edgetpu-objs)
CFLAGS_abrolhos-direct.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-core.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-device.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-device-group.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-firmware.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-platform.o := -DCONFIG_ABROLHOS=1
CFLAGS_edgetpu-thermal.o := -DCONFIG_ABROLHOS=1
