# Build specification for google drivers
obj-$(CONFIG_AUDIOMETRICS) += amplifiers/audiometrics/
obj-$(CONFIG_HAPTICS_CS40L2X) += amplifiers/cs40l25/
obj-$(CONFIG_NITROUS) += bluetooth/broadcom/
obj-$(CONFIG_GOOGLE_BMS) += bms/
obj-$(CONFIG_DRM_SAMSUNG) += display/samsung/
obj-$(CONFIG_ABROLHOS) += edgetpu/drivers/edgetpu/
obj-$(CONFIG_MALI_MIDGARD) += gpu/mali_kbase/
obj-$(CONFIG_MALI_MEMORY_GROUP_MANAGER) += gpu/mali_pixel/
obj-$(CONFIG_LWIS) += lwis/
obj-$(CONFIG_NFC_ST21NFC) += nfc/
obj-$(CONFIG_POWER_RESET_EXYNOS) += power/reset/
obj-$(CONFIG_GOOGLE_TS_COMMON) += touch/common/
obj-$(CONFIG_TOUCHSCREEN_FTS) += touch/fts/ftm5/
obj-$(CONFIG_TOUCHSCREEN_SEC_TS) += touch/sec_ts/
obj-$(CONFIG_WLAN_BCM43752) += wlan/bcm43752/
obj-$(CONFIG_WLAN_BCM4389) += wlan/bcm4389/
